version: "3"

volumes:
  local_postgres_data: 
  local_postgres_data_backups:
  media:
  static:
  nginx:
  initdb:

services:
  nginx:
    image: nginx:alpine
    container_name: nz01
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - media:/src/media
      - static:/src/static
      - nginx:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - djangonetwork
  web:
    image: 8a5d02a1685ccdcf34d68b656988fe5bef463caef81f06db5835200841569edf
    container_name: dz01
    depends_on:
      - db
    volumes:
      - media:/src/media
      - static:/src/static
      - nginx:/config/nginx
    expose:
      - "8000"
    links:
      - redis
    env_file:
      - ./.envs/.django
    networks:
      - djangonetwork
  db:
    image: 680dd4a6f526721a0437e2ffdcf6ddb4de0b86bd57307534ee3a6b37cf4d78de
    container_name: pz01
    env_file:
      - ./.envs/.postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
      - initdb:/docker-entrypoint-initdb.d
    networks:
      - djangonetwork
  redis:
    image: redis:alpine
    container_name: rz01
    ports:
      - "6379:6379"
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge
